apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gau-account-service-hpa
  namespace: bao-${DEPLOY_ENV}-env
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gau-account-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75