apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-kanban-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  PGPOOL_HOST: "${PGPOOL_HOST}"
  PGPOOL_DB: "${PGPOOL_DB}"
  PGPOOL_USER: "${PGPOOL_USER}"
  PGPOOL_PORT: "${PGPOOL_PORT}"
  PGPOOL_URL: "${PGPOOL_URL}"